# Generated by Django 4.1.2 on 2022-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
