# Generated by Django 4.1.2 on 2022-12-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_date_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.DateField(),
        ),
    ]
