# Generated by Django 4.1.2 on 2022-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_date_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
