# Generated by Django 4.1.2 on 2022-12-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_date_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'CalendarYear',
            },
        ),
        migrations.CreateModel(
            name='CalendarMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=4)),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.calendaryear')),
            ],
            options={
                'verbose_name_plural': 'CalendarMonth',
            },
        ),
        migrations.CreateModel(
            name='Calendarday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=4)),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.calendarmonth')),
            ],
            options={
                'verbose_name_plural': 'CalendarDay',
            },
        ),
    ]
