# Generated by Django 4.1.2 on 2022-12-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_calendarday_total_alter_item_date_delete_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Item'},
        ),
    ]
